Repository cDentalCareGroup/web-cdentalcaregroup, pull requests merged in 2024-01, with the labels that each got.

#15 CDCG-30 - Fix-OriginsCard-Footer
  .circleci/config.yml
  .firebaserc
  .github/pull_request_template.md
  README.md
  package-lock.json
  package.json
  src/core/store.ts
  src/pages/origins/Origins.tsx
Labels: bug, issue

#16 CDCG-31 - Fix-OrganizaionCards-Footer
  src/pages/organization/Organizations.tsx
Labels: bug

#18 CDCG-29 - Update/Data-loading-correctly
  src/pages/employees/FormEmployee.tsx
  src/utils/Constants.ts
Labels: issue, improvement

#20 CDCG-13-Add checkbox to filter by status in patients module
  src/pages/patients/Patients.tsx
Labels: refactor, improvement

#21 CDCG-28 - add-Pagination-ModulePads
  src/pages/pad/Pads.tsx
Labels: improvement

#44 CDCG-39- Centralize the use of project colors and themes
  src/App.tsx
  src/pages/auth/Login.tsx
  src/pages/branchoffice/schedules/SchedulesBranchOffice.tsx
  src/pages/components/BackArrow.tsx
  src/pages/components/Sidebar.tsx
  src/utils/ConstantsColors.ts
  tailwind.config.cjs
Labels: improvement, UI / UX

#22 CDCG-5-Update/change doctor while appointment is in process
  src/pages/appointments/components/AppointmentCard.tsx
Labels: improvement, No-activity

#51 CDCG-54 - Create Web ReportsPatient Admin
  src/data/reports/report.ts
  src/pages/reports/Reports.tsx
  src/services/reportsService.ts
  src/utils/Strings.ts
Labels: feature
